# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 13:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название филиала')),
            ],
        ),
        migrations.CreateModel(
            name='LocoInFilial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loco_app.Filial')),
            ],
        ),
        migrations.CreateModel(
            name='LocoSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=30, verbose_name='Серия')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ставка')),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Используйте формат типа: 2017', validators=[django.core.validators.MinValueValidator(2017)], verbose_name='Год')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('loco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loco_app.LocoInFilial')),
            ],
        ),
        migrations.AddField(
            model_name='locoinfilial',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loco_app.LocoSeries'),
        ),
    ]
